[platformio]
default_envs = esp32s3

[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = espidf
monitor_speed = 115200
board_build.partitions = partitions.csv
board_build.esp-idf.sdkconfig_defaults = sdkconfig.defaults

[env:debug]
extends = env:esp32s3
build_flags =
    -DSTICKMINER_DEBUG=1
board_build.esp-idf.sdkconfig_defaults = sdkconfig.defaults sdkconfig.debug

[env:native]
platform = native
test_framework = unity
test_filter = test_host
build_flags =
    -DUNITY_INCLUDE_DOUBLE
    -Icomponents/mining/include
    -lm
test_build_src = yes
build_src_filter = +<../components/mining/src/sha256.c> +<../components/mining/src/work.c>
